export const ACCENT = '#C1502E'

export const PILLARS = [
  {
    num: '01',
    title: 'Rent',
    desc: 'Live with a piece month to month. Swap it out, extend, or fall in love and buy it outright.',
    badge: 'Most popular',
  },
  {
    num: '02',
    title: 'Buy',
    desc: 'Own it forever, with transparent pricing and direct payouts to the artist — no gallery markup.',
    badge: null,
  },
  {
    num: '03',
    title: 'Loan',
    desc: 'Borrow against art you already own for cash, or take a loan to acquire a piece you can\'t pass up.',
    badge: null,
  },
  {
    num: '04',
    title: 'Swap',
    desc: 'Swap a piece in your collection for one from another collector or artist. No cash, no fees, just taste evolving.',
    badge: null,
  },
]

export const ARTWORKS = [
  {
    slug: 'starry-night',
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    medium: 'Oil on canvas',
    year: '1889',
    dimensions: '73.7 × 92.1 cm',
    edition: 'Original',
    location: 'MoMA, New York',
    price: 'From $140/mo',
    rentPrice: '$140/mo',
    buyPrice: 'On request',
    modes: ['Rent', 'Buy'],
    description: 'Painted from the window of the asylum at Saint-Rémy-de-Provence, this swirling night sky is one of the most recognized paintings in Western art.',
    artistBio: 'Vincent van Gogh (1853–1890) was a Dutch Post-Impressionist painter whose bold color and expressive brushwork shaped modern art, despite selling almost nothing in his lifetime.',
  },
  {
    slug: 'water-lilies',
    title: 'Water Lilies',
    artist: 'Claude Monet',
    medium: 'Oil on canvas',
    year: '1906',
    dimensions: '89.9 × 94.1 cm',
    edition: 'Original',
    location: 'Art Institute of Chicago',
    price: 'From $180/mo',
    rentPrice: '$180/mo',
    buyPrice: 'On request',
    modes: ['Rent', 'Swap'],
    description: 'Part of Monet\'s decades-long series painted in his garden at Giverny, dissolving the pond\'s surface into pure color and light.',
    artistBio: 'Claude Monet (1840–1926) was a founder of French Impressionism, dedicated to capturing shifting light and atmosphere directly from nature.',
  },
  {
    slug: 'the-kiss',
    title: 'The Kiss',
    artist: 'Gustav Klimt',
    medium: 'Oil and gold leaf on canvas',
    year: '1908',
    dimensions: '180 × 180 cm',
    edition: 'Original',
    location: 'Belvedere, Vienna',
    price: 'From $220/mo',
    rentPrice: '$220/mo',
    buyPrice: 'On request',
    modes: ['Buy', 'Loan'],
    description: 'Painted during Klimt\'s "Golden Period," this gilded embrace is among the best-known works of Viennese Symbolism.',
    artistBio: 'Gustav Klimt (1862–1918) was an Austrian Symbolist painter and founding member of the Vienna Secession, known for ornamental gold-leaf work.',
  },
  {
    slug: 'girl-pearl-earring',
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    medium: 'Oil on canvas',
    year: 'c. 1665',
    dimensions: '44.5 × 39 cm',
    edition: 'Original',
    location: 'Mauritshuis, The Hague',
    price: 'From $160/mo',
    rentPrice: '$160/mo',
    buyPrice: 'On request',
    modes: ['Rent', 'Swap'],
    description: 'Often called the "Mona Lisa of the North," this tronie captures a fictional young woman in a fleeting glance.',
    artistBio: 'Johannes Vermeer (1632–1675) was a Dutch Golden Age painter celebrated for his mastery of light and quiet domestic scenes.',
  },
  {
    slug: 'the-scream',
    title: 'The Scream',
    artist: 'Edvard Munch',
    medium: 'Tempera and pastel on cardboard',
    year: '1893',
    dimensions: '91 × 73.5 cm',
    edition: 'Original',
    location: 'National Museum, Oslo',
    price: 'From $190/mo',
    rentPrice: '$190/mo',
    buyPrice: 'On request',
    modes: ['Buy', 'Loan'],
    description: 'An anguished figure against a blood-red sky, painted after what Munch described as a sudden attack of dread on an evening walk.',
    artistBio: 'Edvard Munch (1863–1944) was a Norwegian painter whose emotionally charged work anticipated Expressionism.',
  },
  {
    slug: 'great-wave',
    title: 'The Great Wave off Kanagawa',
    artist: 'Katsushika Hokusai',
    medium: 'Woodblock print',
    year: 'c. 1831',
    dimensions: '25.7 × 37.9 cm',
    edition: 'Woodblock print',
    location: 'The Met, New York',
    price: 'From $90/mo',
    rentPrice: '$90/mo',
    buyPrice: 'On request',
    modes: ['Rent', 'Buy'],
    description: 'The best-known print from Hokusai\'s "Thirty-six Views of Mount Fuji" series, pairing a towering wave with the distant sacred mountain.',
    artistBio: 'Katsushika Hokusai (1760–1849) was a Japanese ukiyo-e master whose woodblock prints reshaped how the West saw Japanese art.',
  },
  {
    slug: 'luncheon-boating-party',
    title: 'Luncheon of the Boating Party',
    artist: 'Pierre-Auguste Renoir',
    medium: 'Oil on canvas',
    year: '1881',
    dimensions: '129.9 × 172.7 cm',
    edition: 'Original',
    location: 'The Phillips Collection, Washington D.C.',
    price: 'From $210/mo',
    rentPrice: '$210/mo',
    buyPrice: 'On request',
    modes: ['Rent', 'Swap'],
    description: 'A sunlit gathering of Renoir\'s friends on a terrace above the Seine, capturing the leisure of Impressionist Paris.',
    artistBio: 'Pierre-Auguste Renoir (1841–1919) was a leading French Impressionist known for his luminous, sociable scenes of modern life.',
  },
  {
    slug: 'almond-blossoms',
    title: 'Almond Blossoms',
    artist: 'Vincent van Gogh',
    medium: 'Oil on canvas',
    year: '1890',
    dimensions: '73.3 × 92.4 cm',
    edition: 'Original',
    location: 'Van Gogh Museum, Amsterdam',
    price: 'From $150/mo',
    rentPrice: '$150/mo',
    buyPrice: 'On request',
    modes: ['Loan', 'Buy'],
    description: 'Painted as a gift to celebrate his newborn nephew, this blossoming branch against blue sky is among Van Gogh\'s most joyful works.',
    artistBio: 'Vincent van Gogh (1853–1890) painted this in the final year of his life, drawing on Japanese woodblock prints he admired.',
  },
]

export const TESTIMONIALS = [
  {
    quote: 'I\'ve rotated four pieces through my apartment this year. My walls have never felt this alive — and I haven\'t spent more than $180 in a single month.',
    name: 'Sofía M.',
    role: 'Collector, Palermo',
    stars: 5,
  },
  {
    quote: 'Swap got my work in front of a collector I\'d never have reached through a gallery. Payment hit my account in 48 hours.',
    name: 'Iván R.',
    role: 'Artist',
    stars: 5,
  },
  {
    quote: 'The loan option let me acquire a piece without touching my savings. Paid it down over a year. Would never go back to buying outright.',
    name: 'Carla D.',
    role: 'Collector',
    stars: 5,
  },
]

export const FAQS = [
  {
    q: 'How does renting art actually work?',
    a: 'Pick a piece, choose a monthly term, and we deliver and install it — white-glove service, fully insured. Extend, swap for something new, or buy it at a prorated price whenever you like. No lock-in.',
  },
  {
    q: 'What is Swap?',
    a: 'Swap lets you propose a swap: a piece you own for one in our network you want instead. Our team matches value and handles logistics — no cash changes hands unless there\'s a gap to bridge.',
  },
  {
    q: 'How do art loans work?',
    a: 'Use a piece you already own as collateral for cash, or finance the purchase of a new piece over 6–24 months. Pieces are appraised and insured for the loan term.',
  },
  {
    q: 'How are artists paid?',
    a: 'Artists receive their share within 72 hours of any rental, sale, or loan payout — and keep a majority of every transaction, well above gallery standard. No waiting months for a check.',
  },
  {
    q: 'Do you handle shipping and installation?',
    a: 'Yes. Every rental, purchase, and swap includes white-glove delivery, insurance, and installation in supported cities. Your only job is deciding where it hangs.',
  },
  {
    q: 'Is there a minimum commitment?',
    a: 'No. Rentals start month-to-month with no lock-in. Cancel, swap, or upgrade at any time. We want you to love what\'s on your walls — not feel trapped by it.',
  },
]
